max_iterations: 16

database:
  population_size: 8
  num_islands: 4
  exploitation_ratio: 0.2

llm:
  models:
    - name: gpt-4
      temperature: 0.7

prompt:
  num_top_programs: 2
  num_diverse_programs: 3
