max_iterations: 200

database:
  population_size: 64
  num_islands: 4
  exploitation_ratio: 0.2

llm:
  models:
    - name: mistral-local
      temperature: 0.7
    - name: deepseek-r1-local
      temperature: 0.7

prompt:
  num_top_programs: 2
  num_diverse_programs: 3
